export const actionTypes = {

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGOUT: 'LOGOUT',

    PROFILEINFO_REQUEST: 'PROFILEINFO_REQUEST',
    PROFILEINFO_SUCCESS: 'PROFILEINFO_SUCCESS',
    PROFILEINFO_FAILURE: 'PROFILEINFO_FAILURE',

    BLOGINFO_REQUEST: 'BLOGINFO_REQUEST',
    BLOGINFO_SUCCESS: 'BLOGINFO_SUCCESS',
    BLOGINFO_FAILURE: 'BLOGINFO_FAILURE',

    POST_CREATE_REQUEST: 'POST_CREATE_REQUEST',
    POST_CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
    POST_CREATE_FAILURE: 'POST_CREATE_FAILURE',

    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    USER_CREATE_FAILURE: 'USER_CREATE_FAILURE',

    POST_UPDATE_REQUEST: 'POST_UPDATE_REQUEST',
    POST_UPDATE_SUCCESS: 'POST_UPDATE_SUCCESS',
    POST_UPDATE_FAILURE: 'POST_UPDATE_FAILURE',

    UPDATEUSER_REQUEST: 'UPDATEUSER_REQUEST',
    UPDATEUSER_SUCCESS: 'UPDATEUSER_SUCCESS',
    UPDATEUSER_FAILURE: 'UPDATEUSER_FAILURE',

    OTHERUSER_REQUEST: 'OTHERUSER_REQUEST',
    OTHERUSER_SUCCESS: 'OTHERUSER_SUCCESS',
    OTHERUSER_FAILURE: 'OTHERUSER_FAILURE',
};